volumes:
    pgvector-data:
services:
    lightrag:
        container_name: lightrag
        image: ghcr.io/hkuds/lightrag:latest
        build:
            context: .
            dockerfile: Dockerfile
            tags:
                - ghcr.io/hkuds/lightrag:latest
        ports:
            - "${PORT:-9621}:9621"
        volumes:
            - ./data/rag_storage:/app/data/rag_storage
            - ./data/inputs:/app/data/inputs
            - ./data/tiktoken:/app/data/tiktoken
            - ./config.ini:/app/config.ini
            - ./.env:/app/.env
        env_file:
            - .env
        environment:
            - TIKTOKEN_CACHE_DIR=/app/data/tiktoken
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - lightrag-neo4j
            - lightrag-pgvector
            - lightrag-redis
        restart: unless-stopped
    lightrag-neo4j:
        image: neo4j:enterprise
        volumes:
            - /$HOME/neo4j/logs:/logs
            - /$HOME/neo4j/config:/config
            - /$HOME/neo4j/data:/data
            - /$HOME/neo4j/plugins:/plugins
        environment:
            - NEO4J_AUTH=neo4j/password
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        ports:
            - "7475:7474"
            - "7688:7687"
        restart: unless-stopped
    lightrag-pgvector:
        image: pgvector/pgvector:pg16
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5436:5432"
        volumes:
            - pgvector-data:/var/lib/postgresql/data
        restart: unless-stopped
    lightrag-redis:
        image: redis:6
        ports:
            - "6380:6379"
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
        restart: unless-stopped
